### ISSUE TITLE
6.4 - Grocery Data Pagination - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#166]
![](https://33.media.tumblr.com/2cb78788eeabeff67330750beb4fa46f/tumblr_ml8ozre1VR1qe6fpuo1_500.gif)
### Customer Login
- [x] Login/ Signup features enabled
- [x] Customers able to view items in their cart
### Update pagination
- [x] Pagination implemented server-side only for when users have Javascript turned off 
- [x] Ajax pagination implemented for enhanced experience with Javascript enabled
- [ ] HARD MODE: Allow user to add items to cart
- [ ] HARD MODE: Add catalogue view for available items
- [ ] HARD MODE: Include crud actions for items in cart
### Test
- [x] model tests written and green
- [ ] controller tests written and green
### Style
- [x] Add styles to make site look good!
## Deliverables
- [x] Open a PR on the dev branch for review

Link: https://github.com/andrewtpoe/6.4-grocery-data/pull/1

**Comment by andrewtpoe** [comment]
Pull request has been created to enable easy viewing for fellow students if it is needed. Everything except the JS/AJAX pagination has been pushed up thus far.

**Comment by andrewtpoe** [comment]
Know issue- Items controller tests fail due to devise. No "current_customer" is logged in. Working on a fix.

**Comment by rpearce** [comment]
great gif. SG-1 ftw
