### ISSUE TITLE
2.2 - Inheritance - Michelle Hood

### ISSUE THREAD

**Issue by Meeeeeesh** [tiy-chs-ruby/assignments-june-2015#46]
https://github.com/Meeeeeesh/2.2-Inheritance/pull/2

https://github.com/Meeeeeesh/2.2-Inheritance/tree/dev
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.1-Data-Modeling`
- [x] Create a branch on `2.1-Data-Modeling` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write an ATM program
  - [x] Checkpoint: Create `assignment.rb`
  - [x] Checkpoint: Sketch out similar (but different enough) classes and their attributes
  - [x] Checkpoint: Find shared attributes and pull them in to a `superclass` (aka "parent" class)
  - [x] Checkpoint: Inherit from this superclass
  - [x] Checkpoint: Create a superclass method that applies to all subclasses
  - [x] Checkpoint: Create a method in a child class that accepts an argument and is NOT a getter nor a setter created from `attr_accessor` that overrides its parent method of the same name and then calls `super` with the argument it requires
  - [x] Checkpoint: Given an instance of a subclass, `puts` out its class' `superclass`.
  - [x] Complete: Pushed `assignment.rb`

**Comment by adam-kelsey** [comment]
After reading through your code, I found you the appropriate gif.

https://38.media.tumblr.com/a77b7eca11981570f59757db4566559a/tumblr_mtcstxNE1r1shxe70o1_500.gif

**Comment by Meeeeeesh** [comment]
Better? 
https://github.com/Meeeeeesh/2.2-Inheritance/tree/dev

**Comment by rpearce** [comment]
Best movie ever. Closing issue.
