### ISSUE TITLE
2.3 - Testing - Michelle Hood

### ISSUE THREAD

**Issue by Meeeeeesh** [tiy-chs-ruby/assignments-june-2015#54]
https://github.com/Meeeeeesh/2.3-Testing/tree/dev
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.3-Testing`
- [x] Create a branch on `2.3-Testing` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write an ATM program
  - [x] Checkpoint: Create a `tests.rb` file (or one for each class...)
  - [x] Checkpoint: Set up the file to run MiniTest specs from the command line
  - [x] Checkpoint: `require` your ATM application and/or any other files you might want to test. You can do this in 1 file or multiple test files (and you can even have 1 test file that `require`s all the others and you just run that one!)
  - [x] Checkpoint: Write specs galore!
  - [x] Complete: Pushed `assignment.rb`

**Comment by rpearce** [comment]
Not sure if this is still an issue, but please make sure to create pull requests from your `dev` branch in to `master`.

**Comment by rpearce** [comment]
I also cannot run the code because [these files](https://github.com/Meeeeeesh/2.3-Testing/blob/dev/assignment-test.rb#L3-L6) are missing
