### ISSUE TITLE
3.1 - First Website -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#64]
**PR:**  https://github.com/easmith2/3.1-first-website/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `3.1-First-Website`
- [x] Create a branch on `3.1-First-Website` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Port the images
  - [x] Checkpoint: `index.html` file created
  - [x] Checkpoint: `styles.css` file created
  - [x] Checkpoint: acquire relevant images & place within `images/` folder
  - [x] Checkpoint: create markup based on conceptual drawing(s)
  - [x] Checkpoint: add styles for context & design
  - [x] Checkpoint: slap self on back for excellence
  - [x] Checkpoint: remove instructor's guide comments
  - [x] Complete: pushed all relevant code

**Comment by adam-kelsey** [comment]
Code is looking good! If you used an HR tag instead of making 2 different divs you can put a border around the whole thing and then have an HR tag to have the middle "border", makes your code more compact.

**Comment by rpearce** [comment]
@adam-kelsey feel free to comment on the actual PR instead of the issue so that you can reference line numbers, etc. It also is good for historical accuracy so that, if a revision was made, your comment will be a part of the history.
