### ISSUE TITLE
3.1-Website -Michelle Hood

### ISSUE THREAD

**Issue by Meeeeeesh** [tiy-chs-ruby/assignments-june-2015#65]
https://github.com/Meeeeeesh/3.1-Website/tree/dev
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `3.1-First-Website`
- [x] Create a branch on `3.1-First-Website` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Port the images
  - [x] Checkpoint: `index.html` file created
  - [x] Checkpoint: `styles.css` file created
  - [x] Checkpoint: acquire relevant images & place within `images/` folder
  - [x] Checkpoint: create markup based on conceptual drawing(s)
  - [x] Checkpoint: add styles for context & design
  - [x] Checkpoint: slap self on back for excellence
  - [x] Checkpoint: remove instructor's guide comments
  - [x] Complete: pushed all relevant code

**Comment by rpearce** [comment]
@Meeeeeesh please create a pull request so that I can review this properly.

**Comment by Meeeeeesh** [comment]
https://github.com/Meeeeeesh/3.1-Website/pull/2
