### ISSUE TITLE
3.1 - First Website - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#67]
![](http://media.giphy.com/media/I2PNZEHOpKMDK/giphy.gif)
### Solution

Link: https://github.com/andrewtpoe/3.1-First-Website/pull/1
### Deliverables
- [An issue in the class repo](https://github.com/tiy-chs-ruby/assignments-june-2015) titled `3.1 - First Website -- YOUR NAME` with checkboxes as below under _Requirements_.
- A repository named `3.1-First-Website` containing at least a `README.md` file
- A Pull Request (PR) in your `3.1-First-Website` repo:
  - _from_ branch `dev`
  - _into_ branch master
- A comment on your original Issue with a link to your PR
### Requirements
- Using the image and HTML & CSS templates provided, recreate the image with markup & styles.
- Use the `images/` folder for your used images
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `3.1-First-Website`
- [x] Create a branch on `3.1-First-Website` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Port the images
  - [x] Checkpoint: `index.html` file created
  - [x] Checkpoint: `styles.css` file created
  - [x] Checkpoint: acquire relevant images & place within `images/` folder
  - [x] Checkpoint: create markup based on conceptual drawing(s)
  - [x] Checkpoint: add styles for context & design
  - [x] Checkpoint: slap self on back for excellence
  - [x] Checkpoint: remove instructor's guide comments
  - [x] Complete: pushed all relevant code

**Comment by rpearce** [comment]
@andrewtpoe please create a pull request (which you checked off above) so I can review this properly
