### ISSUE TITLE
3.1 - First Website -- Jamie Simper

### ISSUE THREAD

**Issue by jasimper** [tiy-chs-ruby/assignments-june-2015#68]
https://github.com/jasimper/3.1-First-Website/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `3.1-First-Website`
- [x] Create a branch on `3.1-First-Website` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Port the images
  - [x] Checkpoint: `index.html` file created
  - [x] Checkpoint: `styles.css` file created
  - [x] Checkpoint: acquire relevant images & place within `images/` folder
  - [x] Checkpoint: create markup based on conceptual drawing(s)
  - [x] Checkpoint: add styles for context & design
  - [x] Checkpoint: slap self on back for excellence
  - [x] Checkpoint: remove instructor's guide comments
  - [x] Complete: pushed all relevant code

**Comment by adam-kelsey** [comment]
The code is looking great, if you wanted to mess with the spacing between the two columns you could always add a margin: 50px; or however many you want to the column section. If you want them closer try a negative value.
