### ISSUE TITLE
3.1-my first website - seanpage

### ISSUE THREAD

**Issue by seanmpage** [tiy-chs-ruby/assignments-june-2015#69]
https://github.com/seanmpage/3.1-first-website/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `3.1-First-Website`
- [x] Create a branch on `3.1-First-Website` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Port the images
  - [x] Checkpoint: `index.html` file created
  - [x] Checkpoint: `styles.css` file created
  - [x] Checkpoint: acquire relevant images & place within `images/` folder
  - [x] Checkpoint: create markup based on conceptual drawing(s)
  - [x] Checkpoint: add styles for context & design
  - [x] Checkpoint: slap self on back for excellence
  - [x] Checkpoint: remove instructor's guide comments
  - [x] Complete: pushed all relevant code

**Comment by adam-kelsey** [comment]
Not sure if its just my computer moving the Raised and the number below it to the very left of the box, but if you change your width 50% to auto it fixes that.
