### ISSUE TITLE
3.1 - First Website - Stan

### ISSUE THREAD

**Issue by mcmillanator** [tiy-chs-ruby/assignments-june-2015#71]
PR https://github.com/mcmillanator/3.1-First-Website/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `3.1-First-Website`
- [x] Create a branch on `3.1-First-Website` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Port the images
  - [x] Checkpoint: `index.html` file created
  - [x] Checkpoint: `styles.css` file created
  - [x] Checkpoint: acquire relevant images & place within `images/` folder
  - [x] Checkpoint: create markup based on conceptual drawing(s)
  - [x] Checkpoint: add styles for context & design
  - [x] Checkpoint: slap self on back for excellence
  - [x] Checkpoint: remove instructor's guide comments
  - [x] Complete: pushed all relevant code

**Comment by adam-kelsey** [comment]
You forgot the ; at the end of your max width on your body. Not a big deal unless you want to add the borders to each picture.

**Comment by mcmillanator** [comment]
Fixed!  Thanks Adam!  :D
