### ISSUE TITLE
3.2 - Responsivize -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#74]
**PR:** https://github.com/easmith2/3.2-Responsivize/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `3.2-Responsivize`
- [x] Create a branch on `3.2-Responsivize` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Adjust the website
  - [x] Checkpoint: Added full-height/width background image at any resolution to header/title section
  - [x] Checkpoint: top sections of each half (only when halved) line up accordingly
  - [x] Checkpoint: 2 images added throughout the content
  - [x] Checkpoint: used responsive web design to redefine page elements when the page is `600px` wide or below
  - [x] Checkpoint: validated the page doesn't look like crap
  - [x] Complete: pushed all relevant code

**Comment by adam-kelsey** [comment]
This is just being picky but the fox on the left is being cut off a bit because it is too big, but if you change the background-size: cover; to background-size: 99% 99%; you will get the whole picture without it looking stretched.

**Comment by easmith2** [comment]
I just tried doing that for each type of layout (split and stacked), but the image looked distorted. Can I pick your brain after lecture on this?

**Comment by adam-kelsey** [comment]
yeah sure
