### ISSUE TITLE
3.4-surf michelle

### ISSUE THREAD

**Issue by Meeeeeesh** [tiy-chs-ruby/assignments-june-2015#98]
https://github.com/Meeeeeesh/3.4-surf/pull/1

**Comment by rpearce** [comment]
I have lots of feedback to give you on this, but without it being in PR format, it is more difficult. Also, including the checklist from the homework assignment in here is _part_ of the assignment, for it helps me gauge your status with it. Please include it.

**Comment by rpearce** [comment]
You don't need `target="_self"`.

**Comment by rpearce** [comment]
`<link rel="stylesheet" href="./css/test1.css"/>` should have a space here: `" />`

**Comment by rpearce** [comment]
remember that nesting elements by 2 spaces is very important for your code's legibility

**Comment by rpearce** [comment]
As you can see here,
![image](https://cloud.githubusercontent.com/assets/592876/8634948/b3df68dc-27dc-11e5-8f19-d59c09a8e5c4.png)
the assignment states these deliverables. Your file names are not in accordance with the assignment. We ask you to name them a certain way for a reason. For example, `index.html` is the default that browsers & web servers look for as the root of a website/app.

**Comment by rpearce** [comment]
It looks as though everything in your `test1.css` file was compiled from Sass. Where is the `.scss` file?

**Comment by rpearce** [comment]
Until the homework meets the deliverable criteria, I have to mark this as `requires-revision`
